FROM vim8:base

USER vim

RUN cd /home/vim/.vim/bundle && \
    git clone https://github.com/vim-airline/vim-airline.git && \
    git clone https://github.com/vim-airline/vim-airline-themes.git && \
    git clone https://github.com/thinca/vim-quickrun.git && \
    git clone https://github.com/Shougo/neocomplcache.vim.git && \
    git clone https://github.com/tpope/vim-surround.git && \
    git clone https://github.com/scrooloose/nerdtree.git && \
    git clone https://github.com/scrooloose/syntastic.git

ADD vimrc .vimrc
ADD ~/ .
